name: Test update-major-version-tag

on:
  pull_request:
    branches:
    - main

permissions:
  contents: write

jobs:
  create-test-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create test tag
      id: create_tag
      run: |
        TAG="v100.0.0-${{ github.run_id }}.${{ github.run_attempt }}"
        git tag $TAG
        git push origin $TAG
        echo "tag=$TAG" >> $GITHUB_OUTPUT
    - name: Use update-major-version-tag action
      id: update_major_version_tag
      uses: ./.github/actions/update-major-version-tag
      with:
        tag: ${{ steps.create_tag.outputs.tag }}

    - name: Check major version tag
      run: |
        MAJOR_TAG="v100"
        git fetch --tags
        if git rev-parse "$MAJOR_TAG" >/dev/null 2>&1; then
        echo "Major version tag $MAJOR_TAG exists."
        git show "$MAJOR_TAG"
        else
        echo "Major version tag $MAJOR_TAG does not exist."
        exit 1
        fi

    - name: Cleanup
      run: |
        git tag -d ${{ steps.create_tag.outputs.tag }}
        git push origin :refs/tags/${{ steps.create_tag.outputs.tag }}
        MAJOR_TAG="v100"
        git tag -d $MAJOR_TAG
        git push origin :refs/tags/$MAJOR_TAG
