name: Update major version tag
description: |
  This action updates or creates a major version tag based on the latest semver tag pushed to the repository. If the major version tag already exists, it updates it to point to the latest commit; otherwise, it creates a new major version tag.
  Make sure that this action is only triggered for semver tags.
  This action is used for managing major version tags in a GitHub repository, ensuring that the major version tag always points to the latest commit of the corresponding major version.
  This is useful for repositories that contain shared workflows.
  Normally, you can only refer to a shared workflow by the full tag, but this action allows you to refer to the major version tag, which is more convenient.

  ```yaml
  on:
    push:
      tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  ```

  This actions requires the following permissions:
  ```yaml
    permissions:
      contents: write
  ```
author: EIDP
inputs:
  tag:
    description: >
      The source tag to create the major version tag for. This must be a semver tag like `v1.2.3`.
      If not provided, it will use the tag from the GitHub context.
    required: false
    default: ''
outputs:
  major_tag:
    description: >
      The created or updated major version tag, e.g., `v1` for a tag like `v1.2.3`.
    value: ${{ steps.update-major-version-tag.outputs.major_tag }}
runs:
  using: 'composite'
  steps:
  - name: Update major version tag
    id: update-major-version-tag
    uses: actions/github-script@v7
    with:
      script: |
        const providedTag = '${{ inputs.tag }}';
        const tag = providedTag ? providedTag : context.ref.replace('refs/tags/', '');
        const match =  tag.match(/^v(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z\-\.]+))?(?:\+([0-9A-Za-z\-\.]+))?$/);
        if (!match) {
          console.log("Not a semver tag, skipping.");
          return;
        }
        const majorTag = `v${match[1]}`;
        const commitSha = context.sha;
  
        // Check if tag exists
        try {
          await github.rest.git.getRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `tags/${majorTag}`
          });
  
          await github.rest.git.updateRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `tags/${majorTag}`,
            sha: commitSha,
            force: true
          });
          console.log(`Updated tag ${majorTag} to ${commitSha}`);
        } catch (err) {
          // Create if it doesn’t exist
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${majorTag}`,
            sha: commitSha
          });
          console.log(`Created tag ${majorTag} at ${commitSha}`);
        }

        core.setOutput('major_tag', majorTag);
