name: Check Workflow Status
description: |
  Checks the status of specified jobs using the needs context.
  This is useful for configuring required status checks in GitHub branch protection rules.
  Using this action, you only need to configure a single job that checks the status of multiple jobs, rather than configuring each job individually in the branch protection rules.

  This action requires a GitHub token with the following permissions:
  ```yaml
    permissions:
      contents: read
      actions: read
      pull-requests: read # Only needed if you use the `required-files-changed` input
  ```
author: EIDP
inputs:
  jobs:
    description: >
      Comma-separated list of job names to check status for.
    required: true
    default: ''
  github-token:
    description: >
      GitHub token to authenticate API requests.
    required: true
  requires-files-changed:
    description: >
      Comma-separated list of file paths or globs. If specified and this workflow runs on a PR with no matching files changed, it exits successfully.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13.7'
        
    - name: Check Workflow Status
      id: check_status
      shell: bash
      run: |
        python3 "${{ github.action_path }}/check_status.py"
      env:
        INPUT_JOBS: ${{ inputs.jobs }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_REQUIRES_FILES_CHANGED: ${{ inputs.requires-files-changed }}