name: Check Workflow Status
description: |
  Checks the status of specified jobs using the needs context.
  This is useful for configuring required status checks in GitHub branch protection rules.
  Using this action, you only need to configure a single job that checks the status of multiple jobs, rather than configuring each job individually in the branch protection rules.

  This action requires a GitHub token with the following permissions:
  ```yaml
    permissions:
      contents: read
      actions: read
  ```
author: EIDP
inputs:
  github-token:
    description: >
      GitHub token to authenticate API requests.
    required: true
  timeout-minutes:
    description: >
      Maximum time to wait for all jobs to complete (in minutes). Default: 30 minutes.
    required: false
    default: '30'
  initial-wait-seconds:
    description: >
      Time to wait for the first job to appear in the workflow (in seconds). Default: 10 seconds.
    required: false
    default: '10'
  skipped-jobs-succeed:
    description: >
      Whether to treat skipped jobs as successful. Set to 'false' to fail if any job is skipped. Default: true.
    required: false
    default: 'true'
  poll-interval-seconds:
    description: >
      Time between polling API for job status updates (in seconds). Default: 5 seconds.
    required: false
    default: '5'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.13.7'
        
    - name: Check Workflow Status
      id: check_status
      shell: bash
      run: |
        python3 "${{ github.action_path }}/check_status.py"
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
        INPUT_INITIAL_WAIT_SECONDS: ${{ inputs.initial-wait-seconds }}
        INPUT_SKIPPED_JOBS_SUCCEED: ${{ inputs.skipped-jobs-succeed }}
        INPUT_POLL_INTERVAL_SECONDS: ${{ inputs.poll-interval-seconds }}