name: Check Workflow Status
description: |
  Checks the status of specified jobs using the needs context.
  This is useful for configuring required status checks in GitHub branch protection rules.
  Using this action, you only need to configure a single job that checks the status of multiple jobs, rather than configuring each job individually in the branch protection rules.

  This action requires a GitHub token with the following permissions:
  ```yaml
    permissions:
      contents: read
      actions: read
  ```

author: EIDP
inputs:
  jobs:
    description: >
      Comma-separated list of job names to check status for.
    required: true
    default: ''
  github-token:
    description: >
      GitHub token to authenticate API requests.
    required: true

runs:
  using: composite
  steps:
  - name: Check Workflow Status
    id: check_status
    shell: bash
    run: |
      jobs="${{ inputs.jobs }}"
      IFS=',' read -ra JOB_LIST <<< "$jobs"
      repo="${{ github.repository }}"
      run_id="${{ github.run_id }}"
      api_url="https://api.github.com/repos/$repo/actions/runs/$run_id/jobs"
      response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ inputs.github-token }}" "$api_url")
      http_status="${response: -3}"
      response_body="${response:0:${#response}-3}"
      if [[ "$http_status" != "200" ]]; then
      echo "HTTP response status: $http_status"
      fi
      if [[ "$(echo "$response_body" | jq -r '.jobs')" == "null" ]]; then
        echo "No jobs found in API response. Check permissions, token, and run ID."
        exit 1
      fi
      for job in "${JOB_LIST[@]}"; do
        job=$(echo "$job" | xargs)
        job_found=""
        max_attempts=10
        attempt=1
        while [[ -z "$job_found" && $attempt -le $max_attempts ]]; do
        job_found=$(echo "$response_body" | jq -r ".jobs[] | select(.name==\"$job\") | .name")
        if [[ -z "$job_found" ]]; then
            echo "Job '$job' not found. Attempt $attempt/$max_attempts. Waiting..."
            sleep 2
            response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ inputs.github-token }}" "$api_url")
            http_status="${response: -3}"
            response_body="${response:0:${#response}-3}"
            ((attempt++))
          fi
        done
        if [[ -z "$job_found" ]]; then
          echo "Jobs found: $(echo "$response_body" | jq -r '.jobs[].name' | paste -sd "," -)"
          echo "Job '$job' does not exist after $max_attempts attempts."
          exit 1
        fi
        while true; do
          result=$(echo "$response_body" | jq -r ".jobs[] | select(.name==\"$job\") | .conclusion")
          if [[ "$result" == "null" ]]; then
            echo "Job '$job' is still in progress. Waiting..."
            sleep 1
            response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ inputs.github-token }}" "$api_url")
            http_status="${response: -3}"
            response_body="${response:0:${#response}-3}"
            if [[ "$http_status" != "200" ]]; then
              echo "HTTP response status: $http_status"
            fi
          else
            if [[ "$result" == "success" ]]; then
              echo "Job '$job' completed successfully."
            elif [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
              echo "Job '$job' failed or was cancelled."
              exit 1
            fi
            break
          fi
        done
      done
