name: Check Workflow Status
description: |
  Checks the status of specified jobs using the needs context.
  This is useful for configuring required status checks in GitHub branch protection rules.
  Using this action, you only need to configure a single job that checks the status of multiple jobs, rather than configuring each job individually in the branch protection rules.

  This action requires a GitHub token with the following permissions:
  ```yaml
    permissions:
      contents: read
      actions: read
  ```

author: EIDP
inputs:
  jobs:
    description: >
      Comma-separated list of job names to check status for.
    required: true
    default: ''
  github-token:
    description: >
      GitHub token to authenticate API requests.
    required: true

runs:
  using: composite
  steps:
  - name: Check Workflow Status
    id: check_status
    shell: bash
    run: |
      jobs="${{ inputs.jobs }}"
      IFS=',' read -ra JOB_LIST <<< "$jobs"
      repo="${{ github.repository }}"
      run_id="${{ github.run_id }}"
      api_url="https://api.github.com/repos/$repo/actions/runs/$run_id/jobs"
      response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ inputs.github-token }}" "$api_url")
      http_status="${response: -3}"
      response_body="${response:0:${#response}-3}"
      echo "HTTP response status: $http_status"
      if [[ "$(echo "$response_body" | jq -r '.jobs')" == "null" ]]; then
        echo "No jobs found in API response. Check permissions, token, and run ID."
        exit 1
      fi
      for job in "${JOB_LIST[@]}"; do
        job=$(echo "$job" | xargs)
        job_found=$(echo "$response_body" | jq -r ".jobs[] | select(.name==\"$job\") | .name")
        if [[ -z "$job_found" ]]; then
          echo "Job '$job' does not exist."
          exit 1
        fi
        while true; do
          result=$(echo "$response_body" | jq -r ".jobs[] | select(.name==\"$job\") | .conclusion")
          if [[ "$result" == "null" ]]; then
            echo "Job '$job' is still in progress. Waiting..."
            sleep 1
            response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer ${{ inputs.github-token }}" "$api_url")
            http_status="${response: -3}"
            response_body="${response:0:${#response}-3}"
            echo "HTTP response status: $http_status"
          else
            if [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
              echo "Job '$job' failed or was cancelled."
              exit 1
            fi
            break
          fi
        done
      done
