- id: generate-workflow-docs
  name: generate-workflow-docs
  description: Generates documentation for GitHub workflows.
  entry: generate-workflow-docs
  language: python
  types: [text]
  pass_filenames: false
- id: generate-action-docs
  name: generate-action-docs
  description: Generates documentation for GitHub actions.
  entry: generate-action-docs
  language: python
  types: [text]
  pass_filenames: false