name: renovate

on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0/30 * * * *'
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: dind-runner-no-pvc
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Log in to Container Registry
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: cr.eidp.io
        username: ${{ secrets. RENOVATE_DOCKER_CR_EIDP_IO_USERNAME }}
        password: ${{ secrets. RENOVATE_DOCKER_CR_EIDP_IO_PASSWORD }}

    - name: Run Renovate
      uses: ./renovate
      with:
        renovate-image: "cr.eidp.io/docker/renovate/renovate"
        renovate-version: "43.272.9"
        github-app-id: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}