name: renovate

on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0/30 * * * *'
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Log in to Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: cr.eidp.io
        username: ${{ secrets. RENOVATE_DOCKER_CR_EIDP_IO_USERNAME }}
        password: ${{ secrets. RENOVATE_DOCKER_CR_EIDP_IO_PASSWORD }}

    - name: Run Renovate
      uses: ./renovate
      with:
        renovate-image: "cr.eidp.io/docker/renovate/renovate"
        renovate-version: "44.8.0"
        github-app-id: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}