name: renovate

on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0/30 * * * *'
  workflow_dispatch: {}

jobs:
  renovate:
    uses: ./.github/workflows/renovate.yml
    with:
      runs-on: dind-runner
    secrets:
      GITHUB_APP_ID: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
      GITHUB_APP_PEM_FILE: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
