name: renovate

on:
  pull_request:
    branches:
    - main
  schedule:
  - cron: '0/30 * * * *'
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: dind-runner-no-pvc
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Log in to Container Registry
      uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
      with:
        registry: cr.eidp.io
        username: ${{ secrets. RENOVATE_DOCKER_CR_EIDP_IO_USERNAME }}
        password: ${{ secrets. RENOVATE_DOCKER_CR_EIDP_IO_PASSWORD }}

    - name: Run Renovate
      uses: ./renovate
      with:
        renovate-image: "cr.eidp.io/docker/renovate/renovate"
        renovate-version: "43.272.9"
        github-app-id: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}