name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

permissions:
  contents: write

jobs:
  test-check-workflow-status:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14.6'

    - name: Run unit tests for check-workflow-status
      working-directory: check-workflow-status
      run: python3 test_check_status.py

  test-commit-sha:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Get commit SHA
      id: commit-sha
      uses: ./commit-sha

    - name: Assert commit SHA
      uses: nick-fields/assert-action@0efd6166067d9c59d89c710fab4f79fb066f8985 # v4.0.1
      with:
        expected: ${{ github.event.pull_request.head.sha || github.sha }}
        actual: ${{ steps.commit-sha.outputs.sha }}

    - name: Assert commit short SHA
      uses: nick-fields/assert-action@0efd6166067d9c59d89c710fab4f79fb066f8985 # v4.0.1
      with:
        expected: ${{ steps.commit-sha.outputs.short-sha }}
        actual: ${{ steps.commit-sha.outputs.sha }}
        comparison: 'startsWith'

  check-workflow-status:
    runs-on: kubernetes-runner
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Check Workflow Status
      id: check-workflow-status
      uses: ./check-workflow-status
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}        