name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

permissions:
  contents: write

jobs:
  test-check-workflow-status:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.14.0'

    - name: Run unit tests for check-workflow-status
      working-directory: check-workflow-status
      run: python3 test_check_status.py

  test-commit-sha:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Get commit SHA
      id: commit-sha
      uses: ./commit-sha

    - name: Assert commit SHA
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2.0.0
      with:
        expected: ${{ github.event.pull_request.head.sha || github.sha }}
        actual: ${{ steps.commit-sha.outputs.sha }}

    - name: Assert commit short SHA
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2.0.0
      with:
        expected: ${{ steps.commit-sha.outputs.short-sha }}
        actual: ${{ steps.commit-sha.outputs.sha }}
        comparison: 'startsWith'

  check-workflow-status:
    runs-on: kubernetes-runner
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Check Workflow Status
      id: check-workflow-status
      uses: ./check-workflow-status
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}        