name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

permissions:
  contents: write

jobs:
  test-update-major-version-tag:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Create test tag
      id: create_tag
      run: |
        TAG="v$((RANDOM % 99001 + 100)).0.0-${{ github.run_id }}.${{ github.run_attempt }}"
        MAJOR_TAG="$(echo $TAG | cut -d. -f1)"
        git tag $TAG
        git push origin $TAG
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "major_tag=$MAJOR_TAG" >> $GITHUB_OUTPUT
    - name: Use update-major-version-tag action
      id: update_major_version_tag
      uses: ./update-major-version-tag
      with:
        tag: ${{ steps.create_tag.outputs.tag }}

    - name: Assert Version Output
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
      with:
        expected: ${{ steps.create_tag.outputs.major_tag }}
        actual: ${{ steps.update_major_version_tag.outputs.major_tag }}

    - name: Check major version tag
      run: |
        MAJOR_TAG="${{ steps.create_tag.outputs.major_tag }}"
        git fetch --tags
        if git rev-parse "$MAJOR_TAG" >/dev/null 2>&1; then
        echo "Major version tag $MAJOR_TAG exists."
        git show "$MAJOR_TAG"
        else
        echo "Major version tag $MAJOR_TAG does not exist."
        exit 1
        fi

    - name: Cleanup
      if: always()
      run: |
        git tag -d ${{ steps.create_tag.outputs.tag }} 2>/dev/null || true
        git push origin :refs/tags/${{ steps.create_tag.outputs.tag }} 2>/dev/null || true

        MAJOR_TAG="${{ steps.create_tag.outputs.major_tag }}"
        git tag -d $MAJOR_TAG 2>/dev/null || true
        git push origin :refs/tags/$MAJOR_TAG 2>/dev/null || true

  test-check-workflow-status:
    runs-on: kubernetes-runner
    permissions:
      contents: read
      actions: read
      pull-requests: read
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.13.7'

    - name: Run unit tests for check-workflow-status
      working-directory: check-workflow-status
      run: python3 test_check_status.py

    - name: check-workflow-status success
      id: check-workflow-status-success
      uses: ./check-workflow-status
      with:
        jobs: 'test-update-major-version-tag'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Assert Workflow Status
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
      with:
        expected: success
        actual: ${{ steps.check-workflow-status-success.outcome }}

    - name: check-workflow-status non-existent-job
      id: check-workflow-status-non-existent-job
      uses: ./check-workflow-status
      with:
        jobs: 'test-update-major-version-tag,non-existent-job'
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Assert Workflow Status
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
      with:
        expected: failure
        actual: ${{ steps.check-workflow-status-non-existent-job.outcome }}

    - name: failing-job
      id: failing-job
      continue-on-error: true
      run: exit 1

    - name: check-workflow-status failed
      id: check-workflow-status-failed
      uses: ./check-workflow-status
      with:
        jobs: 'test-update-major-version-tag,failing-job'
        github-token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Assert Workflow Status
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
      with:
        expected: failure
        actual: ${{ steps.check-workflow-status-failed.outcome }}

    - name: check-workflow-status succeeds when no required files are present
      id: check-workflow-status-required-files
      uses: ./check-workflow-status
      with:
        jobs: 'failing-job'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        requires-files-changed: this/does/not.exist,neither/**/does.this

    - name: Assert Workflow Status
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
      with:
        expected: success
        actual: ${{ steps.check-workflow-status-required-files.outcome }}

  test-commit-sha:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Get commit SHA
      id: commit-sha
      uses: ./commit-sha

    - name: Assert commit SHA
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
      with:
        expected: ${{ github.event.pull_request.head.sha || github.sha }}
        actual: ${{ steps.commit-sha.outputs.sha }}

    - name: Assert commit short SHA
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2
      with:
        expected: ${{ steps.commit-sha.outputs.short-sha }}
        actual: ${{ steps.commit-sha.outputs.sha }}
        comparison: 'startsWith'

  check-workflow-status:
    runs-on: kubernetes-runner
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Check Workflow Status
      id: check-workflow-status
      uses: ./check-workflow-status
      with:
        jobs: 'test-update-major-version-tag,test-check-workflow-status,test-commit-sha'
        github-token: ${{ secrets.GITHUB_TOKEN }}