name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

permissions:
  contents: write

jobs:
  test-check-workflow-status:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: '3.14.1'

    - name: Run unit tests for check-workflow-status
      working-directory: check-workflow-status
      run: python3 test_check_status.py

  test-commit-sha:
    runs-on: kubernetes-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Get commit SHA
      id: commit-sha
      uses: ./commit-sha

    - name: Assert commit SHA
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2.0.0
      with:
        expected: ${{ github.event.pull_request.head.sha || github.sha }}
        actual: ${{ steps.commit-sha.outputs.sha }}

    - name: Assert commit short SHA
      uses: nick-fields/assert-action@aa0067e01f0f6545c31755d6ca128c5a3a14f6bf # v2.0.0
      with:
        expected: ${{ steps.commit-sha.outputs.short-sha }}
        actual: ${{ steps.commit-sha.outputs.sha }}
        comparison: 'startsWith'

  check-workflow-status:
    runs-on: kubernetes-runner
    permissions:
      contents: read
      actions: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Check Workflow Status
      id: check-workflow-status
      uses: ./check-workflow-status
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}        