name: Common workflow

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: >
          GitHub token used for authentication in various actions.
          This is automatically provided by GitHub Actions and does not need to be set manually.
        required: true

jobs:
  assign-pr-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR Labels
      id: assign-labels
      uses: mauroalderete/action-assign-labels@v1
      with:
        pull-request-number: ${{ github.event.pull_request.number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        conventional-commits: |
          conventional-commits:
            - type: 'fix'
              nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
              labels: ['bug']
            - type: 'feature'
              nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
              labels: ['feature']
            - type: 'breaking_change'
              nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
              labels: ['BREAKING CHANGE']
        maintain-labels-not-matched: false
        apply-changes: true