name: common

on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The type of runner to use for the workflow. Defaults to 'ubuntu-latest'.
          You can specify a different runner if needed.
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  assign-pr-labels:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Assign PR Labels
      id: assign-labels
      uses: mauroalderete/action-assign-labels@671a4ca2da0f900464c58b8b5540a1e07133e915 # v1
      with:
        pull-request-number: ${{ github.event.pull_request.number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        conventional-commits: |
          conventional-commits:
          - type: 'fix'
            nouns: ['FIX', 'Fix', 'fix', 'FIXED', 'Fixed', 'fixed']
            labels: ['bug']
          - chore: 'chore'
            nouns: ['CHORE', 'Chore', 'chore']
            labels: ['enhancement']
          - type: 'feature'
            nouns: ['FEATURE', 'Feature', 'feature', 'FEAT', 'Feat', 'feat']
            labels: ['feature']
          - type: 'breaking_change'
            nouns: ['BREAKING CHANGE', 'BREAKING', 'MAJOR']
            labels: ['BREAKING CHANGE']
        maintain-labels-not-matched: false
        apply-changes: true