name: renovate

on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The type of runner to use for the workflow.
          You can specify a different runner if needed.
        required: false
        type: string
        default: ubuntu-latest
      renovate-config-repo:
        description: >
          The repository where the Renovate configuration is stored. 
          This must be the repository name **without** the owner, e.g., `renovate-config`.
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      renovate-config-repo-ref:
        description: >
          The branch or tag of the Renovate configuration repository to use.
        required: false
        type: string
        default: ${{ github.event.repository.default_branch }}
      renovate-config-file-path:
        description: >
          The full path to the Renovate configuration file, relative to the root.
        required: false
        type: string
        default: renovate-config/renovate.js
      renovate-image:
        description: >
          The Renovate Docker image name to use. 
          If omitted the action will use the `ghcr.io/renovatebot/renovate:<renovate-version>` Docker image name otherwise.
          If a Docker image name is defined, the action will use that name to pull the image.
        required: false
        type: string
      renovate-version:
        description: >
          The Renovate version to use.
          If omitted the action will use the default version Docker tag. 
          Check [the available tags on Docker Hub](https://hub.docker.com/r/renovate/renovate/tags).
        required: false
        type: string
    secrets:
      GITHUB_APP_ID:
        required: true
        description: >
          The ID of the GitHub App used for Renovate.
          This should be stored as a secret.
      GITHUB_APP_PEM_FILE:
        required: true
        description: >
          The private key (in PEM format) of the GitHub App used for Renovate.
jobs:
  renovate:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Get token
      id: get_token
      uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2
      with:
        private-key: ${{ secrets.GITHUB_APP_PEM_FILE }}
        app-id: ${{ secrets.GITHUB_APP_ID }}
        owner: ${{ github.repository_owner }}

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Checkout Renovate Config Repo
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        repository: ${{ github.repository_owner }}/${{ inputs.renovate-config-repo }}
        ref: ${{ inputs.renovate-config-repo-ref }}
        token: ${{ steps.get_token.outputs.token }}
        path: ./renovate-config

    - name: Renovate
      uses: renovatebot/github-action@6927a58a017ee9ac468a34a5b0d2a9a9bd45cac3 # v43.0.11
      env:
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
        HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME || '' }}
        HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD || '' }}
        RENOVATE_LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL || 'INFO' }}
        RENOVATE_REPOSITORIES: "eidp/${{ github.event.repository.name }}"
      with:
        configurationFile: "./${{ inputs.renovate-config-file-path }}"
        renovate-image: ${{ inputs.renovate-image }}
        renovate-version: ${{ inputs.renovate-version }}
        token: '${{ steps.get_token.outputs.token }}'
        env-regex: "^(?:RENOVATE_\\w+|GITHUB_TOKEN|HARBOR_\\w+)$"