name: renovate

on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The type of runner to use for the workflow.
          You can specify a different runner if needed.
        required: false
        type: string
        default: ubuntu-latest
      renovate-config-file-path:
        description: >
          The full path to the Renovate configuration file, relative to the root.
        required: false
        type: string
        default: renovate.json
      renovate-image:
        description: >
          The Renovate Docker image name to use. 
          If omitted the action will use the `ghcr.io/renovatebot/renovate:<renovate-version>` Docker image name otherwise.
          If a Docker image name is defined, the action will use that name to pull the image.
        required: false
        type: string
      renovate-version:
        description: >
          The Renovate version to use.
          If omitted the action will use the default version Docker tag. 
          Check [the available tags on Docker Hub](https://hub.docker.com/r/renovate/renovate/tags).
        required: false
        type: string
    secrets:
      GITHUB_APP_ID:
        required: true
        description: >
          The ID of the GitHub App used for Renovate.
          This should be stored as a secret.
      GITHUB_APP_PEM_FILE:
        required: true
        description: >
          The private key (in PEM format) of the GitHub App used for Renovate.
jobs:
  renovate:
    runs-on: ${{ inputs.runs-on }}
    steps:

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Run Renovate
      uses: ./renovate
      with:
        github-app-id: ${{ secrets.RENOVATE_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.RENOVATE_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}