name: renovate

on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The type of runner to use for the workflow.
          You can specify a different runner if needed.
        required: false
        type: string
        default: ubuntu-latest
      renovate-config-repo:
        description: >
          The repository where the Renovate configuration is stored. 
          This must be the repository name **without** the owner, e.g., `renovate-config`.
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      renovate-config-repo-ref:
        description: >
          The branch or tag of the Renovate configuration repository to use.
        required: false
        type: string
        default: ${{ github.event.repository.default_branch }}
      renovate-config-file-path:
        description: >
          The full path to the Renovate configuration file within the configuration repository, relative to the root.
        required: false
        type: string
        default: renovate.js
      renovate-image:
        description: >
          The Renovate Docker image name to use. 
          If omitted the action will use the `ghcr.io/renovatebot/renovate:<renovate-version>` Docker image name otherwise.
          If a Docker image name is defined, the action will use that name to pull the image.
        required: false
        type: string
      renovate-version:
        description: >
          The Renovate version to use.
          If omitted the action will use the default version Docker tag. 
          Check [the available tags on Docker Hub](https://hub.docker.com/r/renovate/renovate/tags).
        required: false
        type: string
    secrets:
      GITHUB_APP_ID:
        required: true
        description: >
          The ID of the GitHub App used for Renovate.
          This should be stored as a secret.
      GITHUB_APP_PEM_FILE:
        required: true
        description: >
          The private key (in PEM format) of the GitHub App used for Renovate.
jobs:
  renovate:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Get token
      id: get_token
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
      with:
        private-key: ${{ secrets.GITHUB_APP_PEM_FILE }}
        app-id: ${{ secrets.GITHUB_APP_ID }}
        owner: ${{ github.repository_owner }}
        repositories: ${{ github.event.repository.name }}, ${{ inputs.renovate-config-repo }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout Renovate Config Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/${{ inputs.renovate-config-repo }}
        ref: ${{ inputs.renovate-config-repo-ref }}
        token: ${{ steps.get_token.outputs.token }}
        path: ./renovate-config

    - name: Renovate
      uses: renovatebot/github-action@e3c9b63dabe11d616d9a5e9c19064ec6560369c0 # v43.0.6
      env:
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
      with:
        configurationFile: ./renovate-config/${{ inputs.renovate-config-file-path }}
        renovate-image: ${{ inputs.renovate-image }}
        renovate-version: ${{ inputs.renovate-version }}
        token: '${{ steps.get_token.outputs.token }}'
        env-regex: "^(?:RENOVATE_\\w+|GITHUB_TOKEN)$"